site_name: 'Phase文档'
site_description: 'Phase的文档'
site_author: 'lightyears1998'
site_url: 'https://lightyears1998.github.io/phase-docs/'

repo_name: 'lightyears1998/phase-docs'
repo_url: 'https://github.com/lightyears1998/phase-docs'

theme:
  name: 'material'
  language: 'zh'
  logo: 'assets/logo.png'
  favicon: 'assets/logo.png'
  palette:
    primary: 'blue'
    accent: 'red'
  font:
    text: 'Source Han Serif'
    code: 'Source Code Pro'

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
