site_name: 'DayPrimer文档'
site_description: 'DayPrimer的文档'
site_author: 'lightyears1998'
site_url: 'https://lightyears1998.github.io/day-primer-docs/'

repo_name: 'lightyears1998/day-primer-docs'
repo_url: 'https://github.com/lightyears1998/day-primer-docs'

theme:
  name: 'material'
  language: 'zh'
  logo: 'assets/logo.png'
  favicon: 'assets/logo.png'
  palette:
    primary: 'indigo'
    accent: 'deep orange'
  font:
    code: 'Source Code Pro'
    text: 'Noto Sans SC'

markdown_extensions:
  - admonition
  - codehilite:
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true
