site_name: 'DayPrimer文档'
site_description: 'DayPrimer的文档'
site_author: 'lightyears1998'
site_url: 'https://lightyears1998.github.io/day-primer-docs/'

repo_name: 'lightyears1998/day-primer-docs'
repo_url: 'https://github.com/lightyears1998/day-primer-docs'

theme:
  name: 'material'
  language: 'zh'
  logo: 'assets/logo.png'
  favicon: 'assets/logo.png'
  palette:
    primary: '#7b8dc7'
    accent: '#ec6760'
  font:
    code: 'Source Code Pro'

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
